const CHANGE_PLAYER = 'CHANGE_PLAYER',
      INCREMENT_TURN_COUNTER = 'INCREMENT_TURN_COUNTER',
      UPDATE_OWNED_SQUARES = 'UPDATE_OWNED_SQUARES',
      WIN_STATUS = 'WIN_STATUS';

export { CHANGE_PLAYER, INCREMENT_TURN_COUNTER, UPDATE_OWNED_SQUARES, WIN_STATUS };