const CHANGE_PLAYER = 'CHANGE_PLAYER',
      RESET_PLAYER = 'RESET_PLAYER',
      INCREMENT_TURN_COUNTER = 'INCREMENT_TURN_COUNTER',
      RESET_TURN_COUNTER = 'RESET_TURN_COUNTER',
      UPDATE_OWNED_SQUARES = 'UPDATE_OWNED_SQUARES',
      RESET_OWNED_SQUARES = 'RESET_OWNED_SQUARES',
      WIN_STATUS = 'WIN_STATUS',
      RESET_WIN_STATUS = 'RESET_WIN_STATUS',
      GAME_START = 'GAME_START';

export { CHANGE_PLAYER, RESET_PLAYER,
         INCREMENT_TURN_COUNTER, RESET_TURN_COUNTER,
         UPDATE_OWNED_SQUARES, RESET_OWNED_SQUARES,
         WIN_STATUS, RESET_WIN_STATUS,
         GAME_START };